baseURL = 'https://blog.luxrime.top/'
languageCode = 'zh-cn'
title = "RookieIO's Tech Lab"
theme = "PaperMod"

[params]
    defaultTheme = "auto" # è‡ªåŠ¨è·Ÿéšç³»ç»Ÿåˆ‡æ¢é»‘/ç™½æ¨¡å¼
    ShowReadingTime = true # æ˜¾ç¤ºé˜…è¯»æ—¶é—´
    ShowShareButtons = false # åªæœ‰å›½å†…ä¹Ÿæ²¡äººç”¨å›½å¤–çš„åˆ†äº«ï¼Œå…³æ‰æ¸…çˆ½
    ShowPostNavLinks = true # æ˜¾ç¤ºä¸Šä¸€ç¯‡/ä¸‹ä¸€ç¯‡
 # ğŸ‘‡ æ ¸å¿ƒå¼€å…³ï¼šå¼€å¯ä»£ç å—çš„å¤åˆ¶æŒ‰é’®
    ShowCodeCopyButtons = true
    

    [params.homeInfoParams]
        Title = "Hi there ğŸ‘‹"
        Content = "æ¬¢è¿æ¥åˆ°æˆ‘çš„ Arch Linux å­¦ä¹ ç¬”è®°"

    # é¡¶éƒ¨å¯¼èˆªæ 
    [[menu.main]]
        identifier = "posts"
        name = "æ–‡ç« "
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "search"
        name = "æœç´¢"
        url = "/search/"
        weight = 20

[markup]
  [markup.highlight]
    # 1. å¼€å¯ä»£ç å—åŠŸèƒ½
    codeFences = true
    guessSyntax = true
    lineNos = false
    
    # 2. æ ¸å¿ƒï¼šæŒ‡å®šä½¿ç”¨ github çš„é«˜äº®é…è‰²æ–¹æ¡ˆï¼ˆä½†è¿™åªä¼šæ”¹å˜æ–‡å­—é¢œè‰²ï¼‰
    style = "github"
    
    # 3. å…³é”®å¼€å…³ï¼šå¿…é¡»è®¾ä¸º falseï¼
    # è¿™æ · Hugo æ‰ä¼šç”Ÿæˆ CSS ç±»åï¼Œè®©æˆ‘ä»¬ä¸‹ä¸€æ­¥çš„ CSS æ–‡ä»¶ç”Ÿæ•ˆã€‚
    # å¦‚æœæ˜¯ trueï¼ŒèƒŒæ™¯è‰²å°±ä¼šè¢«ä¸»é¢˜é”æ­»ã€‚
    noClasses = false