baseURL = 'https://blog.luxrime.top/'
languageCode = 'zh-cn'
title = "RookieIO's Tech Lab"
theme = "PaperMod"

[params]
    defaultTheme = "auto" # è‡ªåŠ¨è·Ÿéšç³»ç»Ÿåˆ‡æ¢é»‘/ç™½æ¨¡å¼
    ShowReadingTime = true # æ˜¾ç¤ºé˜…è¯»æ—¶é—´
    ShowShareButtons = false # åªæœ‰å›½å†…ä¹Ÿæ²¡äººç”¨å›½å¤–çš„åˆ†äº«ï¼Œå…³æ‰æ¸…çˆ½
    ShowPostNavLinks = true # æ˜¾ç¤ºä¸Šä¸€ç¯‡/ä¸‹ä¸€ç¯‡
    
    [params.homeInfoParams]
        Title = "Hi there ğŸ‘‹"
        Content = "æ¬¢è¿æ¥åˆ°æˆ‘çš„ Arch Linux å­¦ä¹ ç¬”è®°"

    # é¡¶éƒ¨å¯¼èˆªæ 
    [[menu.main]]
        identifier = "posts"
        name = "æ–‡ç« "
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "search"
        name = "æœç´¢"
        url = "/search/"
        weight = 20
